# -*- coding: utf-8 -*-
"""testeclonalg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5gg_YMoB4EUBvI3Kmul8sRdW201DQu5
"""

!pip install streamlit pandas folium streamlit-folium geopy

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium
from geopy.distance import geodesic

# Dados simulados
clientes = pd.DataFrame({
    "cliente": [f"C{i}" for i in range(1, 11)],
    "lat": [-20.8465, -20.8448, -20.8431, -20.8479, -20.8457,
             -20.8483, -20.8491, -20.8502, -20.8469, -20.8472],
    "lon": [-41.1195, -41.1211, -41.1182, -41.1223, -41.1175,
             -41.1202, -41.1233, -41.1187, -41.1198, -41.1217],
    "peso": [15, 20, 10, 25, 18, 22, 30, 12, 17, 16]
})

# Coordenada do mercado
mercado = (-20.8450, -41.1200)

# Rotas otimizadas (resultado do CLONALG)
rotas = [[6, 3, 9], [1], [2, 4, 0, 7, 5, 8]]
cores = ['red', 'blue', 'green']

st.title("📦 Dashboard de Roteirização - Perim Supermercados")
st.markdown("### 🚛 Rotas Otimizadas com CLONALG")

# Filtro por veículo
veiculo_selecionado = st.selectbox("Selecione o Veículo:", ["Todos"] + [f"Veículo {i+1}" for i in range(len(rotas))])

# Mapa
m = folium.Map(location=mercado, zoom_start=15)
folium.Marker(mercado, tooltip="Perim Supermercado", icon=folium.Icon(color='black')).add_to(m)

for v_idx, rota in enumerate(rotas):
    if veiculo_selecionado != "Todos" and veiculo_selecionado != f"Veículo {v_idx + 1}":
        continue

    coords = [mercado] + [tuple(clientes.loc[i, ["lat", "lon"]]) for i in rota] + [mercado]
    folium.PolyLine(coords, color=cores[v_idx % len(cores)], weight=5, opacity=0.8,
                    tooltip=f"Veículo {v_idx + 1}").add_to(m)

    for i in rota:
        nome = clientes.loc[i, "cliente"]
        coord = tuple(clientes.loc[i, ["lat", "lon"]])
        folium.Marker(coord, tooltip=f"{nome} (Veículo {v_idx + 1})",
                      icon=folium.Icon(color=cores[v_idx % len(cores)])).add_to(m)

# Mostrar mapa
st_data = st_folium(m, width=700, height=500)

# Tabela de detalhes
st.markdown("### 📋 Detalhes das Entregas")
for v_idx, rota in enumerate(rotas):
    if veiculo_selecionado != "Todos" and veiculo_selecionado != f"Veículo {v_idx + 1}":
        continue
    dados = clientes.loc[rota].copy()
    dados["Veículo"] = f"Veículo {v_idx + 1}"
    st.dataframe(dados.set_index("cliente"))